import type { NextPage } from "next"
import Head from "next/head"
import { useEffect, useState } from "react"

import Layout from "@/components/Layout"
import Textarea from "@/components/ui/Textarea"
import { api } from "@/utils/api"

const NewProject: NextPage = () => {
  const [description, setDescription] = useState<string>("")
  const { mutate, data } = api.chat.chat.useMutation()

  const handleSubmit = () => {
    mutate({
      prompt:
        "I'm trying to build an app that uses AI to suggest the best npm packages available for a project",
    })
  }

  useEffect(() => {
    console.log("ai message: ", data)
  }, [data])

  return (
    <div className="flex min-h-screen flex-col bg-stone-50 text-stone-950 dark:bg-stone-950 dark:text-stone-50">
      <Head>
        <title>aAIDX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col gap-4 w-full">
          <h1 className="w-2/3 leading-tight text-5xl font-bold">
            Let&apos;s start by describing your project
          </h1>
          <Textarea
            placeholder="Describe your project, to get recommendations..."
            value={description}
            onChange={(value) => setDescription(value.toString())}
            onSubmit={handleSubmit}
          />
        </div>
      </Layout>
    </div>
  )
}

export default NewProject
